version: '2'

services:

  node-docker:
    build: .
    image: node-docker
    command: yarn start
    environment:
      NODE_ENV: development
    ports:
      - '4040:4040'
    volumes:
      - .:/home/app/node-docker
      - /home/app/node-docker/node_modules
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
